version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: sku-lifecycle-dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: sk0l1fecycl3
    ports:
      - 5432:5432
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - 9200:9200